swagger: '2.0'

info:
  version: "1.0.0"
  title: beFIT
  description: beFIT is your personalised health index to navigate the city of Berlin.

host: "192.168.194.48:5050"
schemes: ["http"]

consumes:
- application/json
produces:
- application/json

paths:
  /{preference_code}/recommended_locations:
    post:
      summary: Gets locations recommended for a user
      description: |
        Gets recommended locations based on users preferences regarding helath and fitness
      parameters:
        - $ref: '#/parameters/preferenceCode'
        - name: Preferences
          in: body
          description: User's preferences
          schema:
            $ref: "#/definitions/Preference"
      responses:
        200:
          description: Recommended locations
          schema:
            type: array
            items:
              $ref: "#/definitions/Locations"
        400:
          description: 'Requested objects could not be found. More information in accompanying message.'

parameters:
  preferenceCode:
    name: preferenceCode
    in: query
    description: Preferences of the user regarding health and fitness
    type: string
    required: true

definitions:
  Preference:
    type: object
    properties:
      crs:
        type: string
        description: whether sports is preferred outside or not
      what:
        type: string
        description: fitness or crossfit or ...
  PointOfInterest:
    type: object
    properties:
      lat:
        type: number
        format: float
      lon:
        type: number
        format: float
      category:
        type: string
      name:
        type: string
  Location:
    type: object
    properties:
      center_lat:
        type: number
        format: float
      center_lon:
        type: number
        format: float
      radius:
        type: integer
      poi:
        type: array
        items:
          $ref: "#/definitions/PointOfInterest"
  Locations:
    type: array
    items:
      $ref: "#/definitions/Location"

  Error:
    properties:
      code:
        type: integer
      message:
        type: string

responses:
  UserCar400ErrorResponse:
    description: Request was invalid.
    schema:
      $ref: '#/definitions/Error'




